<block> 		::= 	"STARTING_BLOCK_SYMBOL" <instruction> "ENDING_BLOCK_SYMBOL"

<instruction>	::=  	<vardecl>"DELITIMITER"
					 |	<vardecl> "DELITIMITER" <instruction>
					 |	<operation> "DELITIMITER"
					 |	<operation> "DELITIMITER" <instruction>
					 |	<ifblock>
					 |	<ifblock> <instruction>
					 |	<whileblock>
					 |	<whileblock> <instruction>
					 |	<initvar> "DELITIMITER"
					 |	<initvar> "DELITIMITER" <instruction>

<vardecl>		::=		<datatype> <initvar>
					 |	<datatype> "VAR_NAME"
					 |	"CONSTANT" <datatype> <initvar>

<initvar>		::=		"VAR_NAME" "ASSIGN_OPERATOR" <arithmetic>

<arithmetic> 	::=		<arithmetic> "SUM_CARACHTER" <arithmetic>
					 |	<arithmetic> "MULTIPLY_CARACHTER" <arithmetic>
					 |	<arithmetic> "SUBSTRACTION_CARACHTER" <arithmetic>
					 |	<arithmetic> "DIVISION_CARACHTER" <arithmetic>
					 | 	"VAR_NAME"
					 |	"NUMBER"
					 |	"STRING"
					 |	"ARRAY"
					 |	"MATRIX"
					 |	<dereference>

<operation>		::=		"OPERATION_NAME" "START_PARENTHESIS" "END_PARENTHENSIS"
					 |	"OPERATION_NAME" "START_PARENTHESIS" <param> "END_PARENTHENSIS"

<param>			::=		<arithmetic>
					 |	<arithmetic> "COMMA"

<ifblock>		::=		"IF_START" <condition> <block>	
					 | 	"IF_START" <condition> <block> "ELSE_START" <block>
					 |	"IF_START" <condition> <block> "ELSE_START" <ifblock>

<whileblock>	::=		"WHILE_START" <condition> <block>

<condition>		::=		"BOOLEAN"
					 |	"START_PARENTHESIS" <arithmetic> "GREATER_THAN_SYMBOL" <arithmetic> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <arithmetic> "LESS_THAN_SYMBOL" <arithmetic> "END_PARENTHENSIS"	
					 |	"START_PARENTHESIS" <arithmetic> "GREATER_OR_EQUAL_THAN_SYMBOL" <arithmetic> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <arithmetic> "LESS_OR_EQUAL_THAN_SYMBOL" <arithmetic> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <arithmetic> "IS_EQUALS_SYMBOL" <arithmetic> "END_PARENTHENSIS"
					 |	"NOT_SYMBOL" <condition> 
					 |	"START_PARENTHESIS" <arithmetic> "IS_NOT_EQUALS" <arithmetic> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <condition> "OR_SYMBOL" <condition> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <condition>	"AND_SYMBOL" <condition> "END_PARENTHENSIS"
					 |	"START_PARENTHESIS" <condition> "XOR_SYMBOL" <condition> "END_PARENTHENSIS"

<datatype>		::=		"NUMBER"
					 |	"STRING"
					 |	"ARRAY"
					 |	"MATRIX"

<dereference>	::=		"ARRAY" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"  
					 |	"ARRAY" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" 
					 |	"MATRIX" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"     
					 |	"MATRIX" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"   
					 |	"MATRIX" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" 
					 |	"MATRIX" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET"
					 |	"MATRIX" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"  
					 |	"MATRIX" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET"   
					 |	"VAR_NAME" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"
					 |	"VAR_NAME" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET"
					 |	"VAR_NAME" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"    
					 |	"VAR_NAME"	"STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" "STARTING_BRACKET" "NUMBER" "ENDING_BRACKET"  
					 |	"VAR_NAME"	"STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET"
					 |	"VAR_NAME"	"STARTING_BRACKET" "NUMBER" "ENDING_BRACKET" "STARTING_BRACKET" "VAR_NAME" "ENDING_BRACKET"  